# Generated by Django 4.1.2 on 2022-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROBO', '0003_alter_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_items',
            field=models.CharField(default='Not mentioned', max_length=5000),
        ),
    ]
