# Generated by Django 4.1.2 on 2022-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROBO', '0004_remove_order_items_order_quantity_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_items',
            field=models.CharField(max_length=5000),
        ),
    ]
