# Generated by Django 4.0.4 on 2022-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROBO', '0005_alter_order_quantity_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
