# Generated by Django 4.0.4 on 2022-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROBO', '0006_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maincategory',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
