# Generated by Django 4.1.2 on 2022-12-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROBO', '0008_item_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_category',
        ),
    ]
