# Generated by Django 4.1.2 on 2022-12-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ROBO', '0009_remove_item_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_category',
            field=models.ForeignKey(default='Veg - Pizzas', on_delete=django.db.models.deletion.CASCADE, to='ROBO.maincategory'),
        ),
    ]
